### PR TITLE
Change import from ocl to opencamlib

### PR DESCRIPTION
**Pull request by vespakoen**
The 2022 releases use a new import name, because the package is now also published on PyPi and ocl was already taken. (see https://github.com/aewallin/opencamlib/releases/tag/2022.12.17)

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by vespakoen** [comment]
Something is funky, on the osx-arm64 builds FindPython is picking up an old Python v2.7 interpreter, even when providing `-D Python_EXECUTABLE` which points to the right Python interpreter, this might be an issue with FindPython which I will have to debug another time.

**Comment by vespakoen** [comment]
@looooo this is ready to go now, should I rebase the changes into a single commit?

**Comment by looooo** [comment]
> @looooo this is ready to go now, should I rebase the changes into a single commit?

no I guess it's fine this way

**Comment by looooo** [comment]
thank you for the work.

**Pull request merged**
