### PR TITLE
Osx arm64

### PR DESCRIPTION
**Pull request by looooo**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by looooo** [comment]
@conda-forge/core any ideas about this?

```
-- Found Doxygen: $PREFIX/bin/doxygen (found version "") found components: doxygen missing components: dot
CMake Error at /Users/runner/miniforge3/conda-bld/opencamlib_1657556519872/_build_env/share/cmake-3.23/Modules/FindDoxygen.cmake:702 (message):
  Unable to generate Doxyfile template: Bad CPU type in executable
Call Stack (most recent call first):
  CMakeLists.txt:292 (find_package)
```

**Comment by hmaarrfk** [comment]
just disable the docs https://github.com/aewallin/opencamlib/blob/master/src/CMakeLists.txt#L291

**Comment by hmaarrfk** [comment]
Do you really need the docs? If so, the alternative is to add it to the build env, and to pass in the executable that you want to use as a CMAKE argument

doxygen is very nice. they tell what is deprecated, but they don't tell you how to mvoe forward....
https://cmake.org/cmake/help/latest/module/FindDoxygen.html

**Comment by hmaarrfk** [comment]
Feel free to undo my changes 

@conda-forge-admin please rerender

**Comment by looooo** [comment]
@hmaarrfk I am fine without the docs :)

**Pull request merged**
